### ISSUE TITLE
Review and clear up all TODO notes from `multitenancy` branch

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2282]

**Comment by desa** [comment]
# List of TODOs:

- [ ] server/dashboards_test.go:195:          // TODO(desa): this Okay?
- [ ] server/me.go:271:               // TODO(desa): this needs a better name
- [ ] server/me.go:318:               // TODO(desa): better error
- [ ] server/mux.go:203:      // TODO(desa): what to do about admin's being able to set superadmin
- [ ] server/server.go:60:    // TODO(desa): think of a better name
- [ ] server/server.go:305:   // TODO(desa): better name
- [ ] server/service.go:18:   // TODO(desa): better name
- [ ] server/users.go:299:    // TODO(desa): Refactor this https://github.com/influxdata/chronograf/issues/2207
- [ ] chronograf.go:367:      // TODO: Need to test that server throws an error when :interval:'s Resolution or ReportingInterval or zero-value
- [ ] docs/slides/mnGo/mux/mux_go:162:// TODO: this function is not great.  Would be good if providers added their routes.
- [ ] etc/build.py:678:                        # TODO: Check for changelog
- [ ] etc/build.py:690:                                # TODO: check if this is correct
- [ ] etc/config.sample.toml:1:# TODO: wire up configuration files
- [ ] influx/queries/select.go:162:// TODO: I don't think list is right
- [ ] influx/queries/select.go:282:// TODO: Handle subqueries
- [ ] kapacitor/tickscripts_test.go:355:// TODO: Check with Nathaniel if kapacitor can do inequalities on strings
- [ ] server/auth.go:118:             // TODO: seems silly to look up a user twice
- [ ] server/databases_test.go:31:    // TODO: Add test cases.
- [ ] server/databases_test.go:74:    // TODO: Add test cases.
- [ ] server/databases_test.go:117:   // TODO: Add test cases.
- [ ] server/databases_test.go:160:   // TODO: Add test cases.
- [ ] server/databases_test.go:203:   // TODO: Add test cases.
- [ ] server/databases_test.go:246:   // TODO: Add test cases.
- [ ] server/databases_test.go:289:   // TODO: Add test cases.
- [ ] server/databases_test.go:320:   // TODO: Add test cases.
- [ ] server/databases_test.go:340:   // TODO: Add test cases.
- [ ] server/influx.go:71:            // TODO: Here I want to return the error code from influx.
- [ ] server/kapacitors.go:334:       // TODO: validate this data
- [ ] server/kapacitors.go:463:       // TODO: validate this data
- [ ] server/me.go:44:// TODO: This Scheme value is hard-coded temporarily since we only currently
- [ ] server/me.go:145:               // TODO: change to principal.CurrentOrganization
- [ ] server/me.go:260:               // TODO: This Scheme value is hard-coded temporarily since we only currently
- [ ] server/server.go:365:   // TODO: Remove graceful when changing to go 1.8
- [ ] server/users.go:36:     // TODO: This Scheme value is hard-coded temporarily since we only currently

**Comment by ebb-tide** [comment]
update with latest TODOs
