### ISSUE TITLE
Add toggle capability to the hover legend

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2723]
as a user of chronograf
with viewer permissions or higher
when i click on an item in the hover legend
then i expect it to behave the same as the static legend

see #1981 
- [ ] When the user selects from the hover legend all other series are removed from the graph
- [ ] When the user selects an additional series from the legend that one will show
- [ ] When hovering a series in the legend the series highlights in the graph
- [ ] When a user clicks a series in the graph the series is scrolled to in the hover legend
