### ISSUE TITLE
Move precanned dashboards to dashboard page

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2962]
- [ ] Remove concept of a layout
- [ ] Convert existing layouts to dashboards
- [ ] Move new dashboards into default resources dir
- [ ] Update build and release scripts to use these
- [ ] Link host page app to dashboards
- [ ] Add dashboards to a separate section below the user's custom dashboards

The set of default dashboards to show should be determined when a user adds a source to Chronograf by querying the source for specific telegraf data the way it is today. this query would only run once when a source is added and would determine the pre-canned dashboards available to the user.

How do we want to create ids for these dashboards? #3013

**Comment by russorat** [comment]
required for #682

**Comment by russorat** [comment]
comment from a customer: on the system layout, loading all the hosts can cause performance issues when there are a ton of them. something to keep in mind when converting this.

**Comment by russorat** [comment]
Initial mock from @alexpaxton 
![import-dashboard-mockup](https://user-images.githubusercontent.com/4805997/38827245-24d36e02-4167-11e8-9d9c-1c6fd60809e0.png)

**Comment by russorat** [comment]
- [ ] add an option to select import precanned dashboards from the import dashboards screen
- [ ] when a user adds a source, there should be an option to run an auto detection for precanned dashboards. when the user hits yes, we run the query we run today and display the list of dashboards we have found along with the full list if they want to add more.
- [ ] when the user clicks add, the source it created, the dashboards are added
- [ ] there should be an option to each source to rediscover precanned dashboards
- [ ] the host list page should link to these newly created dashboards

**Comment by alexpaxton** [comment]
[create-dashboard-template--v0.pdf](https://github.com/influxdata/chronograf/files/2275827/create-dashboard-template--v0.pdf)

most up to date design

**Comment by russorat** [comment]
tackling this as part of a larger redesign of the UI
