### ISSUE TITLE
Add Custom Meta Query option to template variables

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3637]
The goal of this story is to add a the custom meta query template variable option.

- [x] The user should be able to select a "Custom Meta Query" option from the drop down list when creating a new template variable.
- [x] The user should be able to enter a query into the text box
- [x] Pressing enter (or clicking outside the box) should run the query and preview the results
- [x] If the query is not a meta query (as defined here: https://docs.influxdata.com/influxdb/v1.5/query_language/schema_exploration/) then the user should see an error
- [ ] When the results are displayed, the user should be able to select a default value (see #3635)

[template-variables-config--v5.pdf](https://github.com/influxdata/chronograf/files/2092014/template-variables-config--v5.pdf)

**Comment by russorat** [comment]
this will need an update to the API
 - [ ] add 'influxql' as a type to the TemplateValue in chronograf.go
 - [ ] update the validation function for this new type
