### ISSUE TITLE
Add security configs for Flux into Flux Editor

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3765]
Possibly waiting for design requirements from fluxd team

- [ ] user should be able to configure flux editor with database credentials to use for the query
- [ ] connection should support https
- [ ] As a user, i would like to be able to select unsecure ssl for the fluxd connection (assuming it is possible)

**Comment by russorat** [comment]
no longer relevant
