### ISSUE TITLE
Replace CEO schema explorer with new schema explorer

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3795]
- [ ] UI should be vertical instead of horizontal
- [ ] Use same design & styles as the Flux Editor explorer
- [ ] No checkboxes, items cannot be selected
- [ ] Clicking through the schema explorer will no longer affect the query
- [ ] Hovering over a measurement, field, or tag key reveals a button `+ Add to Query` on the right. Clicking this button will add (if not present) or replace that item in the query

Mediocre mockup of where the button goes:
![screen shot 2018-06-28 at 2 05 15 pm](https://user-images.githubusercontent.com/2433762/42060650-5ecfe6f4-7adc-11e8-902b-f065ce6ed878.png)

This UI change will decouple the builder from the text box so the user must explicitly tell the builder to modify their query

**Comment by russorat** [comment]
this is completed
