### ISSUE TITLE
Implement base V2 of Dashboards

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#3843]
- [x] Implement Cells API (https://github.com/influxdata/chronograf/pull/3842)
- [ ] Implement Template Variables API (this work is being held off until current template variable stuff has settled)
- [ ] Implement Dashboards API (https://github.com/influxdata/chronograf/pull/3947)
