### ISSUE TITLE
Filter out messages in log viewer

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3880]
influxql has 2 regex matching styles, one for matching and one for excluding:

https://docs.influxdata.com/influxdb/v1.5/query_language/spec/#regular-expressions

>  Comparators: =~ matches against !~ doesn’t match against

Currently, the log viewer matches, but, most often I'm filtering out logs so I can see the needle in the haystack.

I like how papertrail does this kind of filtering; basically, you type `-Dropped` to remove all messages that have the word `Dropped` in it.

A word prefixed with - would be transformed as `AND message !~ /Dropped/`

**Comment by ischolten** [comment]
#3889 allows filtering out, but not in the messages column

**Comment by russorat** [comment]
This story should cover the following:
- [ ] when a user types something in to the search bar and hits search, the search bar should clear and the filter should be added to the message field the same way as a user clicking a field value shows up (see image)
- [ ] If a user enters normal text, the filter should use `=~`
- [ ] if the user enters something prefaced with a minus sign (`-prod`) then the filter should use `!~`


![image](https://user-images.githubusercontent.com/4805997/42658026-f3795356-85d8-11e8-8e7a-c6dbf851ce5c.png)

**Comment by chnn** [comment]
There's a potential to reuse some of the UI from annotations for this:

![filtering](https://user-images.githubusercontent.com/638955/43793351-1fbbae6c-9a30-11e8-99f5-f33209d1b2d4.gif)
