### ISSUE TITLE
Support scoping in annotations API

### ISSUE THREAD

**Issue by chnn** [influxdata/chronograf#3905]
Update the annotations API to support user-defined scopes for annotations. 

Broad concept:

- An annotation is either _global_ or _scoped_
- All existing annotations created before this feature ships are _global_
- A _scoped_ annotation has 0 or more user-defined _labels_ associated with it
- A _label_ is just a string, e.g. `"123.host.org"` or `"cluster-456"`—think of it like tags on a blog post, except we won't call them tags since that signifier already has meaning within the context of InfluxDB
- The _scope_ of an annotation refers to the set of labels associated with it

Implementation requirements:

- [ ] A client should be able to fetch all global and all scoped annotations with a single request
- [ ] A client should be able to request only global annotations
- [ ] A client should be able to request only scoped annotations with a particular scope
- [ ] By default, the API should return only global annotations (the existing behavior)
- [ ] Annotation scopes should be stored on the annotation points themselves, i.e. in InfluxDB
- [ ] Add @goller as a reviewer to your PR

cc @russorat

**Comment by chnn** [comment]
Here's a proposal to fulfill the implementation requirements:

### JSON representation

Currently, the JSON representation of annotation looks like:

```json
{
  "id": "b19c707a-ac7b-4518-86e3-0ee52e563934",
  "startTime": "2018-07-09T15:49:07.064Z",
  "endTime": "2018-07-09T15:55:31.827Z",
  "text": "my annotation",
  "type": "",
  "links":  {
     "self": "/chronograf/v1/sources/6/annotations/b19c707a-ac7b-4518-86e3-0ee52e563934"
  }
}
```

The new JSON representation will add a `"scope"` property, an array of strings:

```json
{
  "id": "b19c707a-ac7b-4518-86e3-0ee52e563934",
  "startTime": "2018-07-09T15:49:07.064Z",
  "endTime": "2018-07-09T15:55:31.827Z",
  "text": "my annotation",
  "scope": ["cluster-4", "shard failure"],
  "links":  {
     "self": "/chronograf/v1/sources/6/annotations/b19c707a-ac7b-4518-86e3-0ee52e563934"
  }
}
```

The `"scope"` property is optional. An omitted `"scope"` value or empty `"scope"` array mean that the annotation is globally scoped.

The `"type"` property has been removed, as it is unused and its intended purpose is superseded by the `"scope"` property.

### InfluxDB representation

Internally, the `"scope"` of an annotation will be stored as a `scope` field on the InfluxDB annotation point. This field will be a stringified representation of the scope array items, e.g. `"cluster-4,shard failure"`. Items in the scope array must not contain commas.


### Query arguments

`GET /chronograf/v1/sources/:id/annotations` will by default return all global annotations (those with empty scope / `scope = ''`), which is the current behavior.

This endpoint will support a  new `scope` query parameter, whose argument is a comma-separated list of scope items. For example, a (not yet URL-encoded) request might look like:
```
GET /chronograf/v1/sources/:id/annotations?scope=customer a,incident start'
```
Internally, we will query for the appropriate annotations with something along the lines of
```
SELECT * FROM annotations WHERE scope =~ /customer a/ AND scope ~= /incident start/
```

### Alternatives

This API proposal involves an ad-hoc encoding to translate between

- JSON arrays (e.g. `["cluster-4","error"]`)
- Query parameters and InfluxDB points (`cluster-4,error`)

It's appealing to forgo this approach in favor of leaving encoding concerns entirely up to the client (make `"scope"` a string as well in the JSON representation). While simpler, it would then be difficult to support the `?scope` query parameter.

**Comment by chnn** [comment]
Closing in favor of #4072
