### ISSUE TITLE
Clicking play should scroll logs table to top

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3918]
- [x] Clicking `play` should scroll logs table to top (now)
- [x] Selecting `now` from the time picker should scroll logs table to top and set mode to `play`
- [ ] Scrolling to top should set mode to `play` and time picker to `now`

**Comment by russorat** [comment]
is this in the 1.6.x branch?

**Comment by russorat** [comment]
What's the status on this? is it delivered?
