### ISSUE TITLE
Move fluxd connection to the connections page

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3927]
The goal of this issue is to move the fluxd connection options to the same connections page as the other connections.

As part of this, we can also add security options

- As a user, i would like to add one or more fluxd instances to chronograf
- As a user, i would like to be able to edit existing fluxd connections in chronograf
- As a user, i would like to be able to delete fluxd connections in chronograf
- As a user, i would like to select the specific fluxd connection i want to use in the flux builder
- As a user, i would like to be able to select unsecure ssl for the fluxd connection (assuming it is possible)
- As a user, i would like the default of localhost and port number filled into the ui
- As a user, i would like to know if my config is valid before i save it
- As a user, i would like to know that chronograf can connect to fluxd before closing the configuration page

**Comment by ischolten** [comment]
- [ ] Add flux connection dropdown to manage sources page
- [ ] Ability to add flux connection from dropdown option
- [ ] Ability to add flux connection from button 
- [ ] Ability to set active flux connection
- [ ] Ability to update a flux connection
- [ ] Ability to delete a flux connection from a source
- [ ] Flux page should use the active flux connection for the current source
- [ ] Connecting a flux should bring you to the edit page for that flux
- [ ] Updating flux connection and active flux should be reflected on the flux page
- [ ] Security options?

**Comment by russorat** [comment]
- [ ] @alexpaxton to add designs for the edit connections page for fluxd

**Comment by alexpaxton** [comment]
![test-connection-widget](https://user-images.githubusercontent.com/2433762/43097694-b3f755b0-8e71-11e8-80a1-7e48421449ab.png)

- [ ] Create widget for testing a connection and showing connection status
- [ ] User cannot save an erroneous or untested connection

the widget should use the following markup & styles:

```
<div className="alert alert-dark">
  <span className="icon checkmark" />
  <div className="alert-message">
    {message goes here}
  </div>
</div>
```

**Comment by russorat** [comment]
- [ ] file a feature request for flux to test connections.
