### ISSUE TITLE
Migrate existing add source flow to new wizard component

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3981]
the goal of this issue is to migrate the add a source flow in Chronograf to the new wizard type.

There are two scenarios for this:

This is a brand new user of chronograf starting with an empty db and no connections. After being presented with the log in screen (if they have auth enabled), then will be dropped into the full screen add a source wizard containing the following steps:
1. An informational card describing what they need to do to get started with a button to continue
1. A card which allows them to connect to an influx db source. This will look like the current influx db connection screen. The user should not be able to exit this page until they have a working connection to influxdb.
1. A card which allows them to add one or more kapacitor nodes. This step can be skipped. This should look like our current kapacitor connection config screen but will no include the endpoint configs.

When the user exits, they should be dropped into the status page.

The second scenario is when a user wants to add a brand new source to chronograf. after navigating to the sources page and clicking the add source button, they should see the following screens in an overlay:
1. A card which allows them to connect to an influx db source. This will look like the current influx db connection screen. if the user exits this page without filling in the connection details, the source is not created.
1. A card which allows them to add one or more kapacitor nodes. This step can be skipped. This should look like our current kapacitor connection config screen but will no include the endpoint configs.

the user should be able to edit the connection and the kapacitor connections the same way they do today but they will be dropped back into the wizard to make the edits.

**Comment by ebb-tide** [comment]
- [ ] Add OR edit source
- [ ] Change input components to new ones and form flow to new form flow. 
- [ ] fix setting state issue. 
- [ ] View selectable list of existing kapacitors/fluxes on source. 

- [ ] wizard step should be able to suppress skip link
