### ISSUE TITLE
Add ability to switch Flux sources from the Flux Editor page

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#4020]
[flux-selector--v0.pdf](https://github.com/influxdata/chronograf/files/2229262/flux-selector--v0.pdf)

Probably should tackle alongside #4021 

- [x] Place dropdown in right side of `PageHeader`
- [x] Only users with editor permissions should be able to edit the Flux Source

**Comment by alexpaxton** [comment]
- [ ] Include `Current` in dropdown as an option, which will use the current source (as chosen in the config page)
- [ ] Include `Default` in dropdown as an option, which will use the default source (as chosen in the config page)
