### ISSUE TITLE
Add the ability to specify notes for a cell

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4232]
as a dashboard builder
with editor permissions or higher
when i create a dashboard cell and configure a query
then i would like the ability to add rich notes to that cell for myself or others to understand what the data is a why.

This story would add an optional field to each graph cell that would allow the user to enter markdown text to be displayed along with the data in the cell. If there are no results in the cell, there would be an option to display this markdown text.

this would solve a few issues.
1. this would allow dashboard builders to add context and links to each cell so that dashboard users would know what the error state was and what to do. they could use links in markdown to jump to runbooks or docs if needed. As such, the markdown and the cell data must be able to be visualized at the same time. connect https://github.com/influxdata/chronograf/issues/2594
1. if there is no data being returned, the user would be able to display this markdown text instead. this would help us provide context about why a specific cell in a protoboard is returning no data. It would also help dashboard users know that the dashboard isn't broken, it just has no results. if the user did not specify anything, the standard "No Results" would be shown.
1. we have had many requests for just "notes" cells. if we allow a user to save a cell with no query, this would be a way to accomplish that.

**Comment by alexpaxton** [comment]
I have most of this done in the branch `feat/cell-notes`

![screen shot 2018-08-17 at 5 30 52 pm](https://user-images.githubusercontent.com/2433762/44293780-640ecc00-a243-11e8-966d-dd0ea3b08d1c.png)
Editing a "Note" type cell in the CEO

![moar-markdown-cell](https://user-images.githubusercontent.com/2433762/44293785-6ec96100-a243-11e8-8c4a-696145441de2.gif)
An example markdown cell with a variety of elements

![view-cell-clicky](https://user-images.githubusercontent.com/2433762/44293787-7be65000-a243-11e8-9af3-0b1d38638376.gif)
Viewing a note on a normal (not of type "note") cell. Appears and disappears on hover.

**Comment by alexpaxton** [comment]
### Todo:

- [ ] Add field to `cell` in server code for "show note when no data returned"
- [ ] Add action & reducer for the above option
- [ ] Fine tune security features (The server strips some JS and HTML from the submitted markdown text, however some markdown features are broken because of it)

### Questions

- What kind of restrictions should be enforced in markdown content?
  - Security concerns (XSS attacks)
  - Should users be allowed to display images?
  - Should users be allowed to add links?
- Do we want template variable support in the markdown cell?
- Do we want some sort of shortcode for linking to other dashboards?
  - For example: typing `:dashboard-link-1:` would display a link to dashboard `id: 1` with the dashboard's name as text

**Comment by alexpaxton** [comment]
![show-note-when-no-data](https://user-images.githubusercontent.com/2433762/44372395-8b120b80-a498-11e8-89d2-47f59e541f94.gif)

**Comment by afausti** [comment]
@russorat @alexpaxton The introduction of markdown cells in Chronograf 1.7 was a great addition for the dashboards, thank you for doing that.

Looking forward to have template variable support in markdown cells, that would allow me to add context information to the dashboard which is consistent with the plots shown on other cells.
