### ISSUE TITLE
As a user I can browse and append functions from a menu in the script panel

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#4628]
Add a scrollable menu in the right side of the script panel in the Flux builder:

![image](https://user-images.githubusercontent.com/2433762/47687308-e77e5f00-db9c-11e8-83d5-87cf2a93b531.png)
^ Hover state of function list item

![image](https://user-images.githubusercontent.com/2433762/47687376-23192900-db9d-11e8-9b4f-06e2b0798507.png)
^ Tooltip visible

- [x] Function menu is fixed width
- [x] Does not need to contain exhaustive list of functions, just the most common
- [x] Hovering over a list item reveals helper text to the right of the function name `Click to Add` 
- [x] Clicking a function appends it to the script draft with the example
- [x] Hovering over a function shows tooltip with micro-docs, get content for these from https://github.com/influxdata/flux/blob/master/docs/SPEC.md#filter
- [x] Each tooltip contains a list to a docs page
- [x] Organize functions into groups based on usage (in this example `Aggregations`, `Data`, and `Window`. Groups TBD)
- [x] scrolling should be separate from script
- [x] x to close tooltip

**Comment by nathanielc** [comment]
@alexpaxton Looks great! The organization of the functions seems odd to me. Why are filter, ranger and window all considered "window" functions? If that is just for show then ignore me :)

This would be really nice to have, overall I like the discoverability of it.

**Comment by alexpaxton** [comment]
@nathanielc I wasn't sure how to organize the functions, and which ones to surface in here as "commonly used functions". Any suggestions for organization are appreciated!

**Comment by sanderson** [comment]
@alexpaxton and @nathanielc Whatever organization for functions is decided, I'd like to know so it can be the same in the documentation.

**Comment by russorat** [comment]
- we should add a link to the popover to jump to the docs page for more information
- we should add the ability to add the function to the script with empty params
- a possible data format for this would look like this:
```
[{
  name: 'asdfds',
  args: [
    { name: 'fn', desc: 'asdfsdf' },
 ],
 desc: 'sadfasdf',
 example: 'asdfasdfas',
 category: 'some',
 link: 'http://google.com'
},
...
]
```

**Comment by alexpaxton** [comment]
@russorat I dunno if that is something we would get from an API endpoint or if we just store it statically in the frontend

**Comment by bthesorceror** [comment]
@alexpaxton store statically on the front end, no need to add an extra ajax request for something that is never going to change

**Comment by russorat** [comment]
@alexpaxton let's just do statically for now and we can think about an API if it is super useful for people

**Comment by russorat** [comment]
i'll pull the content from https://github.com/influxdata/docs.influxdata.com/tree/flux/functions/content/flux/v0.7/functions and put it into a static file for this.
