### ISSUE TITLE
As a user I can see a host list view configuration page

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#682]
The idea here is to allow the user to select the tags that populate the table as well as to attach apps to dashboards

**Comment by nhaugo** [comment]
See also #2025

**Comment by nhaugo** [comment]
See also #1790

**Comment by alexpaxton** [comment]
Here's my first pass at a design for this. 

User can create "Host Groups" which appear as vertical tabs with a table inside. Create & Update of groups is accessed via the `+ Create Group` or `Settings` buttons
![manage-hosts--table-v0](https://user-images.githubusercontent.com/2433762/37006176-087a000a-208c-11e8-9b0a-a22cc3352715.png)

Create & Update overlay
![manage-hosts--overlay-v0](https://user-images.githubusercontent.com/2433762/37006227-42276112-208c-11e8-9aa1-a75fb2182a0a.png)

Not sure the details of how the user will narrow scope on the group and a column. I'm guessing it will be kind of like a query so I have a text field for now. There is probably a more elegant way to handle this. Perhaps once the main filter for the group is set, then the column options appear. In each row of the options the user can select a tag or something using a dropdown instead of a text field

**Comment by russorat** [comment]
Initial questions:
 - What would the default screen look like with no configurations?
 - Could someone create groups that match to an App?
 - Could someone create a group from a specified list of things (hosts, apps, ids, containers)
 - Why does the user need to specify the column type?
 - How would the user re-arrange the columns?
 - What does the filter syntax look like? Is this builder just creating a giant query behind the scenes?

**Comment by kye-daishogroup** [comment]
Ill provide feedback from a consumer and Enterprise level.

**Comment by alexpaxton** [comment]
[manage-hosts--v2.pdf](https://github.com/influxdata/chronograf/files/1794399/manage-hosts--v2.pdf)

Here's the latest iteration of the design

Aiming for a flow in which a user can create template variables during the table creation process, which can then be sent along to a dashboard. This should be it fairly smooth to have a pairing between an overview table and a dashboard view

To-Do:
- [ ] Empty State design
- [ ] Add time range and autorefresh to page header
- [ ] What happens to the table columns if a user changes the filter in `Table Settings`?

**Comment by alexpaxton** [comment]
[manage-hosts--v3.pdf](https://github.com/influxdata/chronograf/files/1799043/manage-hosts--v3.pdf)

**Comment by alexpaxton** [comment]
Moved this issue into "In Progress" since it pertains to design, assuming we will break it up into smaller stories during IPM

**Comment by russorat** [comment]
[manage-hosts--v4.pdf](https://github.com/influxdata/chronograf/files/1891414/manage-hosts--v4.pdf)
